version: "3"

services:
  mitmcomp:
    image: ghcr.io/minetaro12/docker-mitmcomp:latest
    restart: always
    working_dir: /mitmcomp
    ports:
      - "8000:8000"
    volumes:
      - ./mitmproxy:/root/.mitmproxy
